on: push
name: npm install and lint
jobs:
  install-and-lint:
    name: install and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - run: npm install
      - run: npm run pretest
